version: '3'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "todolist"
      POSTGRES_USER: "todolist"
      POSTGRES_PASSWORD: "todolist"
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: